### ISSUE TITLE
when calling /status first time, internal server error triggered

### ISSUE THREAD

**Issue by logan-han** [logan-han/twitter-deleter#80]
```
ERROR	Uncaught Exception
{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected end of JSON input",
    "stack": [
        "SyntaxError: Unexpected end of JSON input",
        "    at JSON.parse (<anonymous>)",
        "    at /var/task/index.js:172:25",
        "    at passBackControl (/var/task/node_modules/oauth/lib/oauth.js:390:11)",
        "    at IncomingMessage.<anonymous> (/var/task/node_modules/oauth/lib/oauth.js:409:9)",
        "    at IncomingMessage.emit (events.js:326:22)",
        "    at IncomingMessage.EventEmitter.emit (domain.js:483:12)",
        "    at endReadableNT (_stream_readable.js:1241:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}
```

**Comment by logan-han** [comment]
Resolved it via https://github.com/logan-han/twitter-deleter/pull/232
